let suggestions = [
    "About Us",
    "Contact Info",
    "Elementary School Material",
    "Follow Us",
    "Grade 1",
    "Grade 2",
    "Grade 3",
    "Grade 4",
    "Grade 5",
    "Grade 6",
    "Grade 7",
    "Grade 8",
    "Grade 9",
    "Grade 10",
    "Grade 11",
    "Grade 12",
    "High School Subject",
    "Inpirational Videos",
    "Locations",
    "Middle School Lesson",
    "Motivation",
    "Quick Links",
    "Quotes",
    "Review",
];